steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/yasargcp/gcr.io/yasargcp/github.com/khanyasar/gcplearning:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/yasargcp/gcr.io/yasargcp/github.com/khanyasar/gcplearning:$COMMIT_SHA']
 


